# @package _global_
defaults:
  - /task/screwdriver_wristview
  - _self_

task:
  name: clean_cup_right_arm_wristview_with_rollout
  dataset:
    sources:
      - task_name: clean_cup
        dataset_dir: data/training/clean_cup/contact
        num_episodes: 16
        camera_names: ["cam_right_wrist"]
        contact_edges:
          - right_arm_sponge
        except_idx: []
        label_extend: 150
      - task_name: clean_cup_rollout
        dataset_dir: data/training/clean_cup_rollout/contact
        num_episodes: 6
        camera_names: ["cam_right_wrist"]
        contact_edges:
          - right_arm_sponge
        except_idx: []
